./single.sh: line 17: unexpected EOF while looking for matching `"'
Traceback (most recent call last):
  File "./main_uti.py", line 6, in <module>
    import matplotlib.pyplot as plt
  File "/home/divesh/Desktop/thesis/venv/lib/python3.6/site-packages/matplotlib/pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "/home/divesh/Desktop/thesis/venv/lib/python3.6/site-packages/matplotlib/colorbar.py", line 29, in <module>
    import matplotlib.collections as collections
  File "/home/divesh/Desktop/thesis/venv/lib/python3.6/site-packages/matplotlib/collections.py", line 17, in <module>
    from . import (_path, artist, cbook, cm, colors as mcolors, docstring,
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 764, in get_code
  File "<frozen importlib._bootstrap_external>", line 833, in get_data
KeyboardInterrupt
Traceback (most recent call last):
  File "./main_uti.py", line 6, in <module>
    import matplotlib.pyplot as plt
  File "/home/divesh/Desktop/thesis/venv/lib/python3.6/site-packages/matplotlib/pyplot.py", line 34, in <module>
    from matplotlib import rcsetup, style
  File "/home/divesh/Desktop/thesis/venv/lib/python3.6/site-packages/matplotlib/style/__init__.py", line 1, in <module>
    from .core import use, context, available, library, reload_library
  File "/home/divesh/Desktop/thesis/venv/lib/python3.6/site-packages/matplotlib/style/core.py", line 215, in <module>
    _base_library = load_base_library()
  File "/home/divesh/Desktop/thesis/venv/lib/python3.6/site-packages/matplotlib/style/core.py", line 158, in load_base_library
    library = read_style_directory(BASE_LIBRARY_PATH)
  File "/home/divesh/Desktop/thesis/venv/lib/python3.6/site-packages/matplotlib/style/core.py", line 194, in read_style_directory
    path, use_default_template=False)
  File "/home/divesh/Desktop/thesis/venv/lib/python3.6/site-packages/matplotlib/__init__.py", line 965, in rc_params_from_file
    config_from_file = _rc_params_in_file(fname, fail_on_error)
  File "/home/divesh/Desktop/thesis/venv/lib/python3.6/site-packages/matplotlib/__init__.py", line 897, in _rc_params_in_file
    for line_no, line in enumerate(fd, 1):
  File "/usr/lib/python3.6/codecs.py", line 318, in decode
    def decode(self, input, final=False):
KeyboardInterrupt
Traceback (most recent call last):
  File "./main_uti.py", line 4, in <module>
    import numpy
  File "/home/divesh/Desktop/thesis/venv/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/divesh/Desktop/thesis/venv/lib/python3.6/site-packages/numpy/core/__init__.py", line 78, in <module>
    from . import numeric
  File "/home/divesh/Desktop/thesis/venv/lib/python3.6/site-packages/numpy/core/numeric.py", line 29, in <module>
    from . import shape_base
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap>", line 556, in _init_module_attrs
  File "<frozen importlib._bootstrap>", line 409, in cached
  File "<frozen importlib._bootstrap_external>", line 364, in _get_cached
  File "<frozen importlib._bootstrap_external>", line 301, in cache_from_source
KeyboardInterrupt
Traceback (most recent call last):
  File "./main_uti.py", line 6, in <module>
    import matplotlib.pyplot as plt
  File "/home/divesh/Desktop/thesis/venv/lib/python3.6/site-packages/matplotlib/pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "/home/divesh/Desktop/thesis/venv/lib/python3.6/site-packages/matplotlib/colorbar.py", line 27, in <module>
    import matplotlib.artist as martist
  File "/home/divesh/Desktop/thesis/venv/lib/python3.6/site-packages/matplotlib/artist.py", line 13, in <module>
    from .path import Path
  File "/home/divesh/Desktop/thesis/venv/lib/python3.6/site-packages/matplotlib/path.py", line 17, in <module>
    from . import _path, cbook, rcParams
KeyboardInterrupt
Traceback (most recent call last):
  File "./main_uti.py", line 6, in <module>
    import matplotlib.pyplot as plt
  File "/home/divesh/Desktop/thesis/venv/lib/python3.6/site-packages/matplotlib/pyplot.py", line 34, in <module>
    from matplotlib import rcsetup, style
  File "/home/divesh/Desktop/thesis/venv/lib/python3.6/site-packages/matplotlib/style/__init__.py", line 1, in <module>
    from .core import use, context, available, library, reload_library
  File "/home/divesh/Desktop/thesis/venv/lib/python3.6/site-packages/matplotlib/style/core.py", line 215, in <module>
    _base_library = load_base_library()
  File "/home/divesh/Desktop/thesis/venv/lib/python3.6/site-packages/matplotlib/style/core.py", line 158, in load_base_library
    library = read_style_directory(BASE_LIBRARY_PATH)
  File "/home/divesh/Desktop/thesis/venv/lib/python3.6/site-packages/matplotlib/style/core.py", line 194, in read_style_directory
    path, use_default_template=False)
  File "/home/divesh/Desktop/thesis/venv/lib/python3.6/site-packages/matplotlib/__init__.py", line 965, in rc_params_from_file
    config_from_file = _rc_params_in_file(fname, fail_on_error)
  File "/home/divesh/Desktop/thesis/venv/lib/python3.6/site-packages/matplotlib/__init__.py", line 929, in _rc_params_in_file
    config[key] = val  # try to convert to proper type or skip
  File "/home/divesh/Desktop/thesis/venv/lib/python3.6/site-packages/matplotlib/__init__.py", line 787, in __setitem__
    cval = self.validate[key](val)
  File "/home/divesh/Desktop/thesis/venv/lib/python3.6/site-packages/matplotlib/rcsetup.py", line 892, in validate_cycler
    unknowns = cycler_inst.keys - (set(_prop_validators) | set(_prop_aliases))
KeyboardInterrupt
